name: CodeceptJS

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        config: [desktop, mobile]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn
          npm install wait-on -g
      - name: Start dev server
        run: yarn start &
      - name: curl test
        run: curl http://localhost:8080
      - name: Run tests
        run: wait-on http://localhost:8080 && yarn codecept:${{ matrix.config }}
        env:
          CI: true
