name: 'Firebase Preview'

on:
  pull_request:
    branches: [ 'develop', 'feat/*', 'feature/*' ]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: yarn && APP_UNSAFE_ALLOW_DYNAMIC_CONFIG=1 INCLUDE_EPG_DATA=1 yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
