name: Release - Tag and Build Artifacts

on:
  workflow_dispatch:
  push:
    branches: ['release']

jobs:
  create-new-release-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: yarn

      - name: Build App
        env:
          RELEASE_VERSION: ${{ steps.changelog.outputs.tag }}
        run: |
          yarn build
          cd build
          tar czf ott-web-app-build-${RELEASE_VERSION}.tar.gz public
          zip -r ott-web-app-build-${RELEASE_VERSION}.zip public

      - name: Get current package version
        id: package-version
        run: |
          version=$( jq -r .version package.json)
          echo "current-version=${version}" >> "$GITHUB_OUTPUT"

      - name: Parse Changelog Entry
        id: changelog-reader
        uses: coditory/changelog-parser@v1
        with:
          version: ${{ steps.package-version.outputs.current-version }}
      - name: ECHO
        run: |
          echo "${{steps.package-version.outputs.current-version}}"
          echo "${{steps.changelog-reader.outputs.description}}"

      - name: Append Release Notes
        run: |
          cat <<EOT >> .github/RELEASE_BODY_TEMPLATE.md
          ${{ steps.changelog-reader.outputs.description }}
          EOT
          echo "Appended release notes"

      - name: Release
        uses: ncipollo/release-action@v1
        if: ${{ steps.package-version.outputs.current-version }}
        with:
          artifacts: 'build/ott-web-app-build-*.tar.gz, build/ott-web-app-build-*.zip'
          tag: v${{ steps.package-version.outputs.current-version }}
          bodyFile: '.github/RELEASE_BODY_TEMPLATE.md'
          token: ${{ secrets.github_token }}
