name: Test - Linting

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: yarn install, lint
        run: |
          yarn install
          yarn lint
        env:
          CI: true
